//! Node-Based Visual Shader Graph Engine & WGSL Code Generator
//!
//! Allows designing PBR shaders visually through connected math, noise, fresnel,
//! and procedural nodes, generating optimized WGSL fragment shader code in real-time.

/// Data type flowing through shader node pins
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShaderDataType {
    Float,
    Vec2,
    Vec3,
    Vec4,
}

/// Shader node operations
#[derive(Debug, Clone, PartialEq)]
pub enum ShaderNodeType {
    // Inputs
    Time,
    WorldPosition,
    WorldNormal,
    UvCoords,
    CameraPosition,
    ConstantFloat(f32),
    ConstantColor([f32; 3]),

    // Math
    Add,
    Subtract,
    Multiply,
    Divide,
    Sine,
    Cosine,
    Power,
    Lerp,
    Clamp,
    Normalize,

    // Advanced FX
    Fresnel { power: f32 },
    SimplexNoise { scale: f32 },
    Voronoi { cell_density: f32 },

    // Master Output
    PbrOutput,
}

/// A node in the visual shader graph
#[derive(Debug, Clone, PartialEq)]
pub struct ShaderNode {
    pub id: usize,
    pub name: String,
    pub node_type: ShaderNodeType,
    pub editor_pos: (f32, f32),
}

/// A directed connection between two node pins
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NodeConnection {
    pub from_node: usize,
    pub from_slot: usize,
    pub to_node: usize,
    pub to_slot: usize,
}

/// Visual Node-Based Shader Graph
#[derive(Debug, Clone)]
pub struct ShaderGraph {
    pub name: String,
    pub nodes: Vec<ShaderNode>,
    pub connections: Vec<NodeConnection>,
    pub master_node_id: usize,
}

impl Default for ShaderGraph {
    fn default() -> Self {
        let mut graph = Self {
            name: "Default PBR Graph".into(),
            nodes: Vec::new(),
            connections: Vec::new(),
            master_node_id: 0,
        };

        // Default Master PBR Output
        graph.master_node_id = graph.add_node(ShaderNodeType::PbrOutput, "PBR Master Output", (500.0, 300.0));
        graph
    }
}

impl ShaderGraph {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            ..Default::default()
        }
    }

    pub fn add_node(&mut self, node_type: ShaderNodeType, name: impl Into<String>, pos: (f32, f32)) -> usize {
        let id = self.nodes.len();
        let node = ShaderNode {
            id,
            name: name.into(),
            node_type,
            editor_pos: pos,
        };
        self.nodes.push(node);
        id
    }

    pub fn connect(&mut self, from_node: usize, from_slot: usize, to_node: usize, to_slot: usize) {
        // Remove existing connection to target slot
        self.connections.retain(|c| !(c.to_node == to_node && c.to_slot == to_slot));
        self.connections.push(NodeConnection {
            from_node,
            from_slot,
            to_node,
            to_slot,
        });
    }

    /// Compile the visual node graph into production WGSL shader source
    pub fn generate_wgsl(&self) -> String {
        let mut body = String::new();
        body.push_str("// Auto-generated by Metatopia Visual Shader Graph Engine\n");
        body.push_str("// Graph: ");
        body.push_str(&self.name);
        body.push_str("\n\n");

        body.push_str("fn evaluate_graph(in_world_pos: vec3<f32>, in_normal: vec3<f32>, in_uv: vec2<f32>, time: f32) -> vec4<f32> {\n");

        for node in &self.nodes {
            let var_name = format!("node_{}", node.id);
            match &node.node_type {
                ShaderNodeType::Time => {
                    body.push_str(&format!("    let {} = time;\n", var_name));
                }
                ShaderNodeType::WorldPosition => {
                    body.push_str(&format!("    let {} = in_world_pos;\n", var_name));
                }
                ShaderNodeType::WorldNormal => {
                    body.push_str(&format!("    let {} = in_normal;\n", var_name));
                }
                ShaderNodeType::UvCoords => {
                    body.push_str(&format!("    let {} = in_uv;\n", var_name));
                }
                ShaderNodeType::ConstantFloat(val) => {
                    body.push_str(&format!("    let {} = {:.4};\n", var_name, val));
                }
                ShaderNodeType::ConstantColor(col) => {
                    body.push_str(&format!("    let {} = vec3<f32>({:.4}, {:.4}, {:.4});\n", var_name, col[0], col[1], col[2]));
                }
                ShaderNodeType::Fresnel { power } => {
                    body.push_str(&format!("    let {} = pow(1.0 - max(dot(in_normal, vec3<f32>(0.0, 0.0, 1.0)), 0.0), {:.2});\n", var_name, power));
                }
                ShaderNodeType::Sine => {
                    let input = self.find_input(node.id, 0).unwrap_or("0.0".to_string());
                    body.push_str(&format!("    let {} = sin({});\n", var_name, input));
                }
                ShaderNodeType::Multiply => {
                    let in_a = self.find_input(node.id, 0).unwrap_or("1.0".to_string());
                    let in_b = self.find_input(node.id, 1).unwrap_or("1.0".to_string());
                    body.push_str(&format!("    let {} = {} * {};\n", var_name, in_a, in_b));
                }
                ShaderNodeType::Add => {
                    let in_a = self.find_input(node.id, 0).unwrap_or("0.0".to_string());
                    let in_b = self.find_input(node.id, 1).unwrap_or("0.0".to_string());
                    body.push_str(&format!("    let {} = {} + {};\n", var_name, in_a, in_b));
                }
                ShaderNodeType::Lerp => {
                    let in_a = self.find_input(node.id, 0).unwrap_or("vec3<f32>(0.0)".to_string());
                    let in_b = self.find_input(node.id, 1).unwrap_or("vec3<f32>(1.0)".to_string());
                    let in_t = self.find_input(node.id, 2).unwrap_or("0.5".to_string());
                    body.push_str(&format!("    let {} = mix({}, {}, {});\n", var_name, in_a, in_b, in_t));
                }
                ShaderNodeType::PbrOutput => {
                    let albedo = self.find_input(node.id, 0).unwrap_or("vec3<f32>(0.8, 0.8, 0.8)".to_string());
                    let emissive = self.find_input(node.id, 1).unwrap_or("0.0".to_string());
                    body.push_str(&format!("    let {} = vec4<f32>({}, {});\n", var_name, albedo, emissive));
                }
                _ => {}
            }
        }

        let master_var = format!("node_{}", self.master_node_id);
        body.push_str(&format!("    return {};\n", master_var));
        body.push_str("}\n");
        body
    }

    fn find_input(&self, target_node: usize, target_slot: usize) -> Option<String> {
        self.connections.iter()
            .find(|c| c.to_node == target_node && c.to_slot == target_slot)
            .map(|c| format!("node_{}", c.from_node))
    }
}

// ─── Unit Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_shader_graph_wgsl_generation() {
        let mut graph = ShaderGraph::new("Pulsing Cyber Neon");

        let color_node = graph.add_node(ShaderNodeType::ConstantColor([0.0, 0.9, 1.0]), "Cyan", (100.0, 100.0));
        let time_node = graph.add_node(ShaderNodeType::Time, "Time", (100.0, 200.0));
        let sin_node = graph.add_node(ShaderNodeType::Sine, "Sin Pulse", (250.0, 200.0));

        graph.connect(time_node, 0, sin_node, 0);
        graph.connect(color_node, 0, graph.master_node_id, 0); // Albedo
        graph.connect(sin_node, 0, graph.master_node_id, 1);   // Emissive

        let wgsl = graph.generate_wgsl();
        assert!(wgsl.contains("evaluate_graph"));
        assert!(wgsl.contains("sin(node_"));
        assert!(wgsl.contains("vec3<f32>(0.0000, 0.9000, 1.0000)"));
    }
}
